### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by argus3d** [hollisbrown/blendershortcuts#1]
Hey, this website is  really helpful.
 I have some suggestions to make

. One is the extrude clicking with the right mouse button holding CTRL key. 
![dica1](https://github.com/user-attachments/assets/247457c8-e792-4720-bfdb-54095407849b)
And the other one is add to quick favorites.
![dica2](https://github.com/user-attachments/assets/6903e57e-2c73-42f7-8789-424387ccd8a5)

cheers
Augusto

**Comment by hollisbrown** [comment]
Thank you!

**Comment by hollisbrown** [comment]
Added "Extrude to Cursor", might add quick favs down the road
