### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rehman000** [hollisbrown/blendershortcuts#2]
Instead of calling the G shortcut `Move`, call it `Grab`, that is more intuitive I think. 

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/911d1ca9-8084-4e1a-93df-c6ec436c06d0">

**Comment by hollisbrown** [comment]
I think "move" is more universally understood than "grab" and also in line with the official documentation:
https://docs.blender.org/manual/en/latest/modeling/meshes/editing/mesh/transform/basic.html

**Comment by rehman000** [comment]
Then in this case I think it's best we stick with the official Blender documentation.
